BackOfficeBundle\Entity\DeplacementJour:
    type: entity
    table: deplacement_jour
    indexes:
        fk_deplacement_jour_type_deplacement1_idx:
            columns:
                - type_deplacement_id
        fk_deplacement_jour_deplacement1_idx:
            columns:
                - deplacement_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nbKm:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: nb_km
        montant:
            type: float
            nullable: true
            precision: 10
            scale: 0
        jour:
            type: integer
            nullable: true
            options:
                unsigned: false
        date:
            type: date
            nullable: true
        created:
            type: datetime
            nullable: true
        updated:
            type: datetime
            nullable: true
    manyToOne:
        deplacement:
            targetEntity: Deplacement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                deplacement_id:
                    referencedColumnName: id
            orphanRemoval: false
        typeDeplacement:
            targetEntity: TypeDeplacement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_deplacement_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
