BackOfficeBundle\Entity\TypeUser:
    type: entity
    table: type_user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typeUser:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: type_user
    lifecycleCallbacks: {  }
