BackOfficeBundle\Entity\TypeDeplacement:
    type: entity
    table: type_deplacement
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typeDeplacement:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: type_deplacement
        montant:
            type: float
            nullable: true
            precision: 10
            scale: 0
        created:
            type: datetime
            nullable: true
        updated:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
