BackOfficeBundle\Entity\User:
    type: entity
    table: user
    indexes:
        fk_user_type_user_idx:
            columns:
                - type_user_id
        fk_user_societe1_idx:
            columns:
                - societe_id
        fk_user_service1_idx:
            columns:
                - service_id
        fk_user_ville1_idx:
            columns:
                - ville_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        prenom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        adresse:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        distanceInit:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: distance_init
        created:
            type: datetime
            nullable: true
        updated:
            type: datetime
            nullable: true
    manyToOne:
        service:
            targetEntity: Service
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                service_id:
                    referencedColumnName: id
            orphanRemoval: false
        societe:
            targetEntity: Societe
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                societe_id:
                    referencedColumnName: id
            orphanRemoval: false
        typeUser:
            targetEntity: TypeUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_user_id:
                    referencedColumnName: id
            orphanRemoval: false
        ville:
            targetEntity: Ville
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ville_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
