BackOfficeBundle\Entity\Ville:
    type: entity
    table: ville
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ville:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        cp:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
    lifecycleCallbacks: {  }
