rest:
    resource: "@RestBundle/Resources/config/routing.yml"
    prefix:   /api

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admindep

front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

logout:
    path:     /logout