rest_homepage:
    path:     /
    defaults: { _controller: RestBundle:Default:index }
    
rest_deplacement:
    resource: "@RestBundle/Resources/config/routing/deplacement.yml"
    prefix:   /deplacement
    
rest_deplacements:
    resource: "@RestBundle/Resources/config/routing/deplacements.yml"
    prefix:   /deplacements    