rest_deplacement_index:
    path:     /
    defaults: { _controller: "RestBundle:Deplacement:index" }
    methods:  GET

rest_deplacement_show:
    path:     /{id}/show
    defaults: { _controller: "RestBundle:Deplacement:show" }
    methods:  GET

rest_deplacement_new:
    path:     /new
    defaults: { _controller: "RestBundle:Deplacement:new" }
    methods:  [GET, POST]
